# Window Configuration
# WINDOW_TITLE: The exact title of the scrcpy window (visible at the top of the window)
# To find it: Look at your scrcpy window's title bar, it usually shows your device model
WINDOW_TITLE = "EatventureAuto"
WINDOW_WIDTH = 300 * 1.2
WINDOW_HEIGHT = 650 * 1.2

# Detection Thresholds
MATCH_THRESHOLD = 0.98
RED_ICON_THRESHOLD = 0.94
NEW_LEVEL_RED_ICON_THRESHOLD = 0.95
RED_ICON_MIN_MATCHES = 2
NEW_LEVEL_RED_ICON_MIN_MATCHES = 1
RED_ICON_COLOR_CHECK = True
RED_ICON_COLOR_MIN_RATIO = 1.15
RED_ICON_COLOR_MIN_MEAN = 35
RED_ICON_COLOR_SAMPLE_SIZE = 12
RED_ICON_VERIFY_PADDING = 24
RED_ICON_VERIFY_TOLERANCE = 12
RED_ICON_REFINE_RADIUS = 18
RED_ICON_REFINE_THRESHOLD_DROP = 0.02
RED_ICON_PRIORITY_TEMPLATE_LIMIT = 8
# Process at most this many red icons per FIND_RED_ICONS scan.
# Keeping this at 1 avoids stale multi-icon queues that can trigger
# rapid cross-interactions between unrelated assets.
RED_ICON_MAX_PER_SCAN = 1
STATS_RED_ICON_THRESHOLD = 0.97
SEARCH_INTERVAL = 0.2
CLICK_DELAY = 0.036
MOUSE_MOVE_DELAY = 0.004
MOUSE_DOWN_UP_DELAY = 0.006
DOUBLE_CLICK_DELAY = 0.02
MIN_CLICK_INTERVAL = 0.007
MOUSE_POSITION_TOLERANCE = 2
MOUSE_MOVE_RETRIES = 3
MOUSE_MOVE_RETRY_DELAY = 0.002
MOUSE_TARGET_SETTLE_DELAY = 0.001
MOUSE_TARGET_TIMEOUT = 0.04
MOUSE_TARGET_CHECK_INTERVAL = 0.001
MOUSE_TARGET_HOVER_DELAY = 0.001
MOUSE_STABILIZE_DURATION = 0.004
MOUSE_TARGET_RETRIES = 2
MOUSE_TARGET_CORRECTION_DELAY = 0.001
MOUSE_PRE_CLICK_STABILIZE_BASE = 0.0015
MOUSE_PRE_CLICK_STABILIZE_MAX = 0.012
MOUSE_PRE_CLICK_STABILIZE_DISTANCE_FACTOR = 0.00003
MOUSE_CLICK_RETRY_COUNT = 2
MOUSE_CLICK_RETRY_SETTLE_DELAY = 0.0015

# Directory Paths
TEMPLATES_DIR = "templates"
ASSETS_DIR = "Assets"
LOGS_DIR = "logs"
SCREENSHOTS_DIR = "screenshots"

# Debug and Visualization Settings
DEBUG = True
SAVE_SCREENSHOTS = False

# ShowForbiddenArea: Enables a visual overlay showing forbidden zones in red
# When True, displays red rectangles over areas where the bot won't click
# Useful for debugging and visualizing the forbidden zones configuration
ShowForbiddenArea = False

# Telegram Bot Configuration
# TELEGRAM_ENABLED: Master switch to enable/disable all Telegram notifications
# Set to True if you want to receive any Telegrazm messages from the bot
TELEGRAM_ENABLED = False

# TELEGRAM_BOT_TOKEN: Your Telegram bot API token from @BotFather
# To get one: Message @BotFather on Telegram, use /newbot command
TELEGRAM_BOT_TOKEN = ""

# TELEGRAM_CHAT_ID: Your Telegram chat ID to receive messages
# To get it: Message your bot, then visit: https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates
# Look for "chat":{"id": YOUR_CHAT_ID in the response
TELEGRAM_CHAT_ID = ""

# Game Element Detection
MAX_SEARCH_Y = 660
EXTENDED_SEARCH_Y = 710

# Click Positions (relative to window)
UPGRADE_POS = (320, 726)
NEW_LEVEL_POS = (40, 700)
REDICON_CHECK_POS = (60, 704)
LEVEL_TRANSITION_POS = (183, 561)
IDLE_CLICK_POS = (2, 390)
INIT_CLICK_POS = (180, 472)
STATS_UPGRADE_POS = (270, 304)
STATS_UPGRADE_BUTTON_POS = (310, 698)
SCROLL_START_POS = (170, 410)
SCROLL_END_POS = (170, 160)
NEW_LEVEL_BUTTON_POS = (30, 692)

# Template Matching Settings
UPGRADE_STATION_THRESHOLD = 0.87
UPGRADE_STATION_COLOR_CHECK = False
BOX_THRESHOLD = 0.97
UNLOCK_THRESHOLD = 0.9
NEW_LEVEL_THRESHOLD = 0.98

# Bot Behavior Configuration
RED_ICON_CYCLE_COUNT = 3
STATS_UPGRADE_CLICK_DURATION = 2
STATS_UPGRADE_CLICK_DELAY = 0.006
STATS_ICON_PADDING = 20
CAPTURE_CACHE_TTL = 0.015
NEW_LEVEL_RED_ICON_CACHE_TTL = 0.01
RED_ICON_STABILITY_CACHE_TTL = 0.18
RED_ICON_STABILITY_RADIUS = 14
RED_ICON_STABILITY_MIN_HITS = 2
RED_ICON_STABILITY_MAX_HISTORY = 10
UPGRADE_HOLD_DURATION = 4.6
UPGRADE_CLICK_INTERVAL = 0.008
SCROLL_UP_CYCLES = 2
NEW_LEVEL_INTERRUPT_INTERVAL = 0.02
NEW_LEVEL_MONITOR_INTERVAL = 0.02
NEW_LEVEL_OVERRIDE_COOLDOWN = 0.25
NO_ICON_SCROLL_UP_COUNT = 4
NO_ICON_SCROLL_DOWN_COUNT = 8

# Red Icon Detection Offsets
RED_ICON_OFFSET_X = 10
RED_ICON_OFFSET_Y = 10

# Red Icon Detection Zones
NEW_LEVEL_RED_ICON_X_MIN = 40
NEW_LEVEL_RED_ICON_X_MAX = 60
NEW_LEVEL_RED_ICON_Y_MIN = 665
NEW_LEVEL_RED_ICON_Y_MAX = 680

UPGRADE_RED_ICON_X_MIN = 280
UPGRADE_RED_ICON_X_MAX = 310
UPGRADE_RED_ICON_Y_MIN = 665
UPGRADE_RED_ICON_Y_MAX = 680

# State Machine Settings
STATE_DELAY = 0.006
MAX_SCROLL_CYCLES = 12
MAIN_LOOP_DELAY = 0.005
STATE_MIN_INTERVAL_DEFAULT = 0.007
STATE_MIN_INTERVALS = {
    "FIND_RED_ICONS": 0.009,
    "OPEN_BOXES": 0.009,
    "SCROLL": 0.012,
}
SCROLL_DURATION = 0.55
NO_ICON_SCROLL_DURATION = 0.5
SCROLL_STEP_COUNT = 18
SCROLL_MIN_INTERVAL = 0.02
SCROLL_SETTLE_DELAY = 0.005
SCROLL_SEGMENTS = 12
SCROLL_MIN_SEGMENT_DISTANCE = 24
SCROLL_SEGMENT_SETTLE_DELAY = 0.001
SCROLL_ASSET_SCAN_INTERVAL = 0.006
SCROLL_RED_ICON_MIN_DISTANCE = 56
SCROLL_RED_ICON_THRESHOLD_DROP = 0.01
SCROLL_RED_ICON_MIN_MATCHES = 2
SCROLL_DISTANCE_RATIO = 0.25
SCROLL_ASSET_FULL_SCAN_EVERY = 2
SCROLL_INTERRUPT_ASSET_THRESHOLD = 0.93
SCROLL_INTERRUPT_ASSET_TEMPLATES = (
    "upgradeStation",
    "unlock",
    "box1",
    "box2",
    "box3",
    "box4",
    "box5",
    "RedIcon",
    "RedIcon2",
    "RedIcon3",
    "RedIcon4",
    "RedIcon5",
    "RedIcon6",
    "RedIcon7",
    "RedIcon8",
    "RedIcon9",
    "RedIcon10",
    "RedIcon11",
    "RedIcon12",
    "RedIcon13",
    "RedIcon14",
    "RedIcon15",
    "RedIconNoBG",
)
UPGRADE_SEARCH_INTERVAL = 0.02
UPGRADE_CHECK_INTERVAL = 0.045
IDLE_CLICK_SETTLE_DELAY = 0.006
IDLE_CLICK_COOLDOWN = 0.06
NEW_LEVEL_BUTTON_DELAY = 0.03
NEW_LEVEL_FOLLOWUP_DELAY = 0.02
TRANSITION_POST_CLICK_DELAY = 0.28
TRANSITION_RETRY_DELAY = 0.04
UNLOCK_POST_CLICK_DELAY = 0.1
WAIT_UNLOCK_RETRY_DELAY = 0.06
FORBIDDEN_ICON_MAX_SCROLLS = 3
FORBIDDEN_ICON_SCROLL_DURATION = 0.2
FORBIDDEN_ICON_SCROLL_COOLDOWN = 0.008
ADAPTIVE_TUNER_ENABLED = True
ADAPTIVE_TUNER_ALPHA = 0.2
ADAPTIVE_TUNER_MIN_CLICK_DELAY = 0.035
ADAPTIVE_TUNER_MAX_CLICK_DELAY = 0.11
ADAPTIVE_TUNER_MIN_MOVE_DELAY = 0.003
ADAPTIVE_TUNER_MAX_MOVE_DELAY = 0.012
ADAPTIVE_TUNER_MIN_UPGRADE_INTERVAL = 0.006
ADAPTIVE_TUNER_MAX_UPGRADE_INTERVAL = 0.012
ADAPTIVE_TUNER_MIN_SEARCH_INTERVAL = 0.015
ADAPTIVE_TUNER_MAX_SEARCH_INTERVAL = 0.05
UPGRADE_STATION_REFINE_RADIUS = 28
UPGRADE_STATION_CLICK_REFINE_RADIUS = 18
AI_VISION_ENABLED = True
AI_VISION_ALPHA = 0.2
AI_VISION_ALPHA_MAX = 0.45
AI_VISION_CONFIDENCE_BOOST = 0.3
AI_RED_ICON_THRESHOLD_MIN = 0.92
AI_RED_ICON_THRESHOLD_MAX = 0.985
AI_RED_ICON_MARGIN = 0.01
AI_RED_ICON_MISS_WINDOW = 2
AI_RED_ICON_MISS_STEP = 0.006
AI_NEW_LEVEL_THRESHOLD_MIN = 0.965
AI_NEW_LEVEL_THRESHOLD_MAX = 0.995
AI_NEW_LEVEL_MISS_WINDOW = 2
AI_NEW_LEVEL_MISS_STEP = 0.004
AI_NEW_LEVEL_RED_ICON_THRESHOLD_MIN = 0.92
AI_NEW_LEVEL_RED_ICON_THRESHOLD_MAX = 0.99
AI_NEW_LEVEL_RED_ICON_MISS_WINDOW = 2
AI_NEW_LEVEL_RED_ICON_MISS_STEP = 0.005
AI_UPGRADE_STATION_THRESHOLD_MIN = 0.9
AI_UPGRADE_STATION_THRESHOLD_MAX = 0.99
AI_UPGRADE_STATION_MISS_WINDOW = 2
AI_UPGRADE_STATION_MISS_STEP = 0.005
AI_STATS_UPGRADE_THRESHOLD_MIN = 0.9
AI_STATS_UPGRADE_THRESHOLD_MAX = 0.99
AI_STATS_UPGRADE_MISS_WINDOW = 2
AI_STATS_UPGRADE_MISS_STEP = 0.005
AI_VISION_STATE_FILE = f"{LOGS_DIR}/vision_state.json"
AI_VISION_SAVE_INTERVAL = 1.0
AI_LEARNING_ENABLED = True
AI_LEARNING_STATE_FILE = f"{LOGS_DIR}/learning_state.json"
AI_LEARNING_SAVE_INTERVAL = 1.5
AI_LEARNING_PAIR_WINDOW = 2
AI_LEARNING_BATCH_WINDOW = 7
AI_LEARNING_THREAD_INTERVAL = 0.05
AI_LEARNING_AUTOWRITE_CONFIG = True
AI_LEARNING_MIN_CLICK_DELAY = 0.035
AI_LEARNING_MAX_CLICK_DELAY = 0.12
AI_LEARNING_MIN_MOVE_DELAY = 0.002
AI_LEARNING_MAX_MOVE_DELAY = 0.012
AI_LEARNING_MIN_UPGRADE_INTERVAL = 0.006
AI_LEARNING_MAX_UPGRADE_INTERVAL = 0.013
AI_LEARNING_MIN_SEARCH_INTERVAL = 0.012
AI_LEARNING_MAX_SEARCH_INTERVAL = 0.05
AI_LEARNING_EMA_ALPHA = 0.18
AI_LEARNING_PROFILE_BLEND_TOP_K = 3
AI_LEARNING_MIN_IMPROVEMENT_RATIO = 0.03
AI_LEARNING_APPLY_COOLDOWN = 1.2

# Forbidden Zones Configuration
# These zones prevent the bot from clicking on critical UI elements
# Each zone is defined by: X_MIN, X_MAX, Y_MIN, Y_MAX coordinates
# You can add more zones by following the same pattern (FORBIDDEN_ZONE_7, etc.)

# General forbidden click area (botom bar)
FORBIDDEN_CLICK_X_MIN = 60
FORBIDDEN_CLICK_X_MAX = 280
FORBIDDEN_CLICK_Y_MIN = 668

# Zone 1: Right side menu area
FORBIDDEN_ZONE_1_X_MIN = 290
FORBIDDEN_ZONE_1_X_MAX = 350
FORBIDDEN_ZONE_1_Y_MIN = 93
FORBIDDEN_ZONE_1_Y_MAX = 270

# Zone 2: Left side top menu area
FORBIDDEN_ZONE_2_X_MIN = 0
FORBIDDEN_ZONE_2_X_MAX = 60
FORBIDDEN_ZONE_2_Y_MIN = 50
FORBIDDEN_ZONE_2_Y_MAX = 280

# Zone 3: Left side bottom menu area
FORBIDDEN_ZONE_3_X_MIN = 0
FORBIDDEN_ZONE_3_X_MAX = 60
FORBIDDEN_ZONE_3_Y_MIN = 590
FORBIDDEN_ZONE_3_Y_MAX = 667

# Zone 4: Top center notification area
FORBIDDEN_ZONE_4_X_MIN = 145
FORBIDDEN_ZONE_4_X_MAX = 200
FORBIDDEN_ZONE_4_Y_MIN = 65
FORBIDDEN_ZONE_4_Y_MAX = 110

# Zone 5: Bottom navigation bar
FORBIDDEN_ZONE_5_X_MIN = 55
FORBIDDEN_ZONE_5_X_MAX = 285
FORBIDDEN_ZONE_5_Y_MIN = 660
FORBIDDEN_ZONE_5_Y_MAX = 725

# Zone 6: Top bar area
FORBIDDEN_ZONE_6_X_MIN = 0
FORBIDDEN_ZONE_6_X_MAX = 360
FORBIDDEN_ZONE_6_Y_MIN = 0
FORBIDDEN_ZONE_6_Y_MAX = 70
